import { StoreProvider } from '../store/storeProvider';
import localFont from "next/font/local";
import { Inter } from 'next/font/google'
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: "Cascade",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      {/* <body> */}
      <body> 
        <StoreProvider>{children}</StoreProvider>
      </body>
      {/* </body> */}
    </html>
  );
}
