import { StoreProvider } from "../store/storeProvider";
import "./globals.css";

export const metadata = {
  title: "Cascade",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body> */}
      <body>
        <StoreProvider>{children}</StoreProvider>
      </body>
      {/* </body> */}
    </html>
  );
}
